// Generated by gencpp from file dobot_bringup/AOExecute.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_AOEXECUTE_H
#define DOBOT_BRINGUP_MESSAGE_AOEXECUTE_H

#include <ros/service_traits.h>


#include <dobot_bringup/AOExecuteRequest.h>
#include <dobot_bringup/AOExecuteResponse.h>


namespace dobot_bringup
{

struct AOExecute
{

typedef AOExecuteRequest Request;
typedef AOExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AOExecute
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::AOExecute > {
  static const char* value()
  {
    return "c9ffa71f693aabb4ec23d98e0cce7e29";
  }

  static const char* value(const ::dobot_bringup::AOExecute&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::AOExecute > {
  static const char* value()
  {
    return "dobot_bringup/AOExecute";
  }

  static const char* value(const ::dobot_bringup::AOExecute&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::AOExecuteRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::AOExecute >
template<>
struct MD5Sum< ::dobot_bringup::AOExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::AOExecute >::value();
  }
  static const char* value(const ::dobot_bringup::AOExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::AOExecuteRequest> should match
// service_traits::DataType< ::dobot_bringup::AOExecute >
template<>
struct DataType< ::dobot_bringup::AOExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::AOExecute >::value();
  }
  static const char* value(const ::dobot_bringup::AOExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::AOExecuteResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::AOExecute >
template<>
struct MD5Sum< ::dobot_bringup::AOExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::AOExecute >::value();
  }
  static const char* value(const ::dobot_bringup::AOExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::AOExecuteResponse> should match
// service_traits::DataType< ::dobot_bringup::AOExecute >
template<>
struct DataType< ::dobot_bringup::AOExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::AOExecute >::value();
  }
  static const char* value(const ::dobot_bringup::AOExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_AOEXECUTE_H
