// Generated by gencpp from file dobot_bringup/DigitalOutputsRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_DIGITALOUTPUTSREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_DIGITALOUTPUTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct DigitalOutputsRequest_
{
  typedef DigitalOutputsRequest_<ContainerAllocator> Type;

  DigitalOutputsRequest_()
    : index(0)
    , status(false)  {
    }
  DigitalOutputsRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , status(false)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DigitalOutputsRequest_

typedef ::dobot_bringup::DigitalOutputsRequest_<std::allocator<void> > DigitalOutputsRequest;

typedef boost::shared_ptr< ::dobot_bringup::DigitalOutputsRequest > DigitalOutputsRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::DigitalOutputsRequest const> DigitalOutputsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53b605e6336049068d910c0926e28cde";
  }

  static const char* value(const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53b605e633604906ULL;
  static const uint64_t static_value2 = 0x8d910c0926e28cdeULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/DigitalOutputsRequest";
  }

  static const char* value(const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# index --> 0 - 9\n"
"\n"
"int32 index\n"
"bool status\n"
;
  }

  static const char* value(const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DigitalOutputsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::DigitalOutputsRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_DIGITALOUTPUTSREQUEST_H
