// Generated by gencpp from file dobot_bringup/EnableRobot.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_ENABLEROBOT_H
#define DOBOT_BRINGUP_MESSAGE_ENABLEROBOT_H

#include <ros/service_traits.h>


#include <dobot_bringup/EnableRobotRequest.h>
#include <dobot_bringup/EnableRobotResponse.h>


namespace dobot_bringup
{

struct EnableRobot
{

typedef EnableRobotRequest Request;
typedef EnableRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableRobot
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::EnableRobot > {
  static const char* value()
  {
    return "c8c32a9a172a18b46989544c88798d15";
  }

  static const char* value(const ::dobot_bringup::EnableRobot&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::EnableRobot > {
  static const char* value()
  {
    return "dobot_bringup/EnableRobot";
  }

  static const char* value(const ::dobot_bringup::EnableRobot&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::EnableRobotRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::EnableRobot >
template<>
struct MD5Sum< ::dobot_bringup::EnableRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::EnableRobot >::value();
  }
  static const char* value(const ::dobot_bringup::EnableRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::EnableRobotRequest> should match
// service_traits::DataType< ::dobot_bringup::EnableRobot >
template<>
struct DataType< ::dobot_bringup::EnableRobotRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::EnableRobot >::value();
  }
  static const char* value(const ::dobot_bringup::EnableRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::EnableRobotResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::EnableRobot >
template<>
struct MD5Sum< ::dobot_bringup::EnableRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::EnableRobot >::value();
  }
  static const char* value(const ::dobot_bringup::EnableRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::EnableRobotResponse> should match
// service_traits::DataType< ::dobot_bringup::EnableRobot >
template<>
struct DataType< ::dobot_bringup::EnableRobotResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::EnableRobot >::value();
  }
  static const char* value(const ::dobot_bringup::EnableRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_ENABLEROBOT_H
