// Generated by gencpp from file dobot_bringup/GetErrorID.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_GETERRORID_H
#define DOBOT_BRINGUP_MESSAGE_GETERRORID_H

#include <ros/service_traits.h>


#include <dobot_bringup/GetErrorIDRequest.h>
#include <dobot_bringup/GetErrorIDResponse.h>


namespace dobot_bringup
{

struct GetErrorID
{

typedef GetErrorIDRequest Request;
typedef GetErrorIDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetErrorID
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::GetErrorID > {
  static const char* value()
  {
    return "21732a31ce08e00841e34036c6b93272";
  }

  static const char* value(const ::dobot_bringup::GetErrorID&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::GetErrorID > {
  static const char* value()
  {
    return "dobot_bringup/GetErrorID";
  }

  static const char* value(const ::dobot_bringup::GetErrorID&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::GetErrorIDRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::GetErrorID >
template<>
struct MD5Sum< ::dobot_bringup::GetErrorIDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetErrorID >::value();
  }
  static const char* value(const ::dobot_bringup::GetErrorIDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetErrorIDRequest> should match
// service_traits::DataType< ::dobot_bringup::GetErrorID >
template<>
struct DataType< ::dobot_bringup::GetErrorIDRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetErrorID >::value();
  }
  static const char* value(const ::dobot_bringup::GetErrorIDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::GetErrorIDResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::GetErrorID >
template<>
struct MD5Sum< ::dobot_bringup::GetErrorIDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetErrorID >::value();
  }
  static const char* value(const ::dobot_bringup::GetErrorIDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetErrorIDResponse> should match
// service_traits::DataType< ::dobot_bringup::GetErrorID >
template<>
struct DataType< ::dobot_bringup::GetErrorIDResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetErrorID >::value();
  }
  static const char* value(const ::dobot_bringup::GetErrorIDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_GETERRORID_H
