// Generated by gencpp from file dobot_bringup/GetPoseRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_GETPOSEREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_GETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct GetPoseRequest_
{
  typedef GetPoseRequest_<ContainerAllocator> Type;

  GetPoseRequest_()
    : user()
    , tool()  {
    }
  GetPoseRequest_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , tool(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _user_type;
  _user_type user;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _tool_type;
  _tool_type tool;





  typedef boost::shared_ptr< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseRequest_

typedef ::dobot_bringup::GetPoseRequest_<std::allocator<void> > GetPoseRequest;

typedef boost::shared_ptr< ::dobot_bringup::GetPoseRequest > GetPoseRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::GetPoseRequest const> GetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::GetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::GetPoseRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user &&
    lhs.tool == rhs.tool;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::GetPoseRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::GetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2233a20fac1bba9267ebb17f7126cb92";
  }

  static const char* value(const ::dobot_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2233a20fac1bba92ULL;
  static const uint64_t static_value2 = 0x67ebb17f7126cb92ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/GetPoseRequest";
  }

  static const char* value(const ::dobot_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] user\n"
"int32[] tool\n"
;
  }

  static const char* value(const ::dobot_bringup::GetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.tool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::GetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::GetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "user[]" << std::endl;
    for (size_t i = 0; i < v.user.size(); ++i)
    {
      s << indent << "  user[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.user[i]);
    }
    s << indent << "tool[]" << std::endl;
    for (size_t i = 0; i < v.tool.size(); ++i)
    {
      s << indent << "  tool[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.tool[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_GETPOSEREQUEST_H
