// Generated by gencpp from file dobot_bringup/JointMovJ.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_JOINTMOVJ_H
#define DOBOT_BRINGUP_MESSAGE_JOINTMOVJ_H

#include <ros/service_traits.h>


#include <dobot_bringup/JointMovJRequest.h>
#include <dobot_bringup/JointMovJResponse.h>


namespace dobot_bringup
{

struct JointMovJ
{

typedef JointMovJRequest Request;
typedef JointMovJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMovJ
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::JointMovJ > {
  static const char* value()
  {
    return "1017b68b63f136fff53e96a209a4d563";
  }

  static const char* value(const ::dobot_bringup::JointMovJ&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::JointMovJ > {
  static const char* value()
  {
    return "dobot_bringup/JointMovJ";
  }

  static const char* value(const ::dobot_bringup::JointMovJ&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::JointMovJRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::JointMovJ >
template<>
struct MD5Sum< ::dobot_bringup::JointMovJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::JointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::JointMovJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::JointMovJRequest> should match
// service_traits::DataType< ::dobot_bringup::JointMovJ >
template<>
struct DataType< ::dobot_bringup::JointMovJRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::JointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::JointMovJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::JointMovJResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::JointMovJ >
template<>
struct MD5Sum< ::dobot_bringup::JointMovJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::JointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::JointMovJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::JointMovJResponse> should match
// service_traits::DataType< ::dobot_bringup::JointMovJ >
template<>
struct DataType< ::dobot_bringup::JointMovJResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::JointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::JointMovJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_JOINTMOVJ_H
