// Generated by gencpp from file dobot_bringup/pause.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_PAUSE_H
#define DOBOT_BRINGUP_MESSAGE_PAUSE_H

#include <ros/service_traits.h>


#include <dobot_bringup/pauseRequest.h>
#include <dobot_bringup/pauseResponse.h>


namespace dobot_bringup
{

struct pause
{

typedef pauseRequest Request;
typedef pauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pause
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::pause > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::dobot_bringup::pause&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::pause > {
  static const char* value()
  {
    return "dobot_bringup/pause";
  }

  static const char* value(const ::dobot_bringup::pause&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::pauseRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::pause >
template<>
struct MD5Sum< ::dobot_bringup::pauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::pause >::value();
  }
  static const char* value(const ::dobot_bringup::pauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::pauseRequest> should match
// service_traits::DataType< ::dobot_bringup::pause >
template<>
struct DataType< ::dobot_bringup::pauseRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::pause >::value();
  }
  static const char* value(const ::dobot_bringup::pauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::pauseResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::pause >
template<>
struct MD5Sum< ::dobot_bringup::pauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::pause >::value();
  }
  static const char* value(const ::dobot_bringup::pauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::pauseResponse> should match
// service_traits::DataType< ::dobot_bringup::pause >
template<>
struct DataType< ::dobot_bringup::pauseResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::pause >::value();
  }
  static const char* value(const ::dobot_bringup::pauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_PAUSE_H
