// Generated by gencpp from file dobot_bringup/RelJointMovJRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct RelJointMovJRequest_
{
  typedef RelJointMovJRequest_<ContainerAllocator> Type;

  RelJointMovJRequest_()
    : offset1(0.0)
    , offset2(0.0)
    , offset3(0.0)
    , offset4(0.0)
    , offset5(0.0)
    , offset6(0.0)
    , paramValue()  {
    }
  RelJointMovJRequest_(const ContainerAllocator& _alloc)
    : offset1(0.0)
    , offset2(0.0)
    , offset3(0.0)
    , offset4(0.0)
    , offset5(0.0)
    , offset6(0.0)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef double _offset1_type;
  _offset1_type offset1;

   typedef double _offset2_type;
  _offset2_type offset2;

   typedef double _offset3_type;
  _offset3_type offset3;

   typedef double _offset4_type;
  _offset4_type offset4;

   typedef double _offset5_type;
  _offset5_type offset5;

   typedef double _offset6_type;
  _offset6_type offset6;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelJointMovJRequest_

typedef ::dobot_bringup::RelJointMovJRequest_<std::allocator<void> > RelJointMovJRequest;

typedef boost::shared_ptr< ::dobot_bringup::RelJointMovJRequest > RelJointMovJRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::RelJointMovJRequest const> RelJointMovJRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offset1 == rhs.offset1 &&
    lhs.offset2 == rhs.offset2 &&
    lhs.offset3 == rhs.offset3 &&
    lhs.offset4 == rhs.offset4 &&
    lhs.offset5 == rhs.offset5 &&
    lhs.offset6 == rhs.offset6 &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b1e1d884e18f48808ed6cd8a6abf307";
  }

  static const char* value(const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b1e1d884e18f488ULL;
  static const uint64_t static_value2 = 0x08ed6cd8a6abf307ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/RelJointMovJRequest";
  }

  static const char* value(const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 offset1\n"
"float64 offset2\n"
"float64 offset3\n"
"float64 offset4\n"
"float64 offset5\n"
"float64 offset6\n"
"string[] paramValue\n"
;
  }

  static const char* value(const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset1);
      stream.next(m.offset2);
      stream.next(m.offset3);
      stream.next(m.offset4);
      stream.next(m.offset5);
      stream.next(m.offset6);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelJointMovJRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::RelJointMovJRequest_<ContainerAllocator>& v)
  {
    s << indent << "offset1: ";
    Printer<double>::stream(s, indent + "  ", v.offset1);
    s << indent << "offset2: ";
    Printer<double>::stream(s, indent + "  ", v.offset2);
    s << indent << "offset3: ";
    Printer<double>::stream(s, indent + "  ", v.offset3);
    s << indent << "offset4: ";
    Printer<double>::stream(s, indent + "  ", v.offset4);
    s << indent << "offset5: ";
    Printer<double>::stream(s, indent + "  ", v.offset5);
    s << indent << "offset6: ";
    Printer<double>::stream(s, indent + "  ", v.offset6);
    s << indent << "paramValue[]" << std::endl;
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      s << indent << "  paramValue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.paramValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJREQUEST_H
