// Generated by gencpp from file dobot_bringup/RelJointMovJ.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJ_H
#define DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJ_H

#include <ros/service_traits.h>


#include <dobot_bringup/RelJointMovJRequest.h>
#include <dobot_bringup/RelJointMovJResponse.h>


namespace dobot_bringup
{

struct RelJointMovJ
{

typedef RelJointMovJRequest Request;
typedef RelJointMovJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelJointMovJ
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::RelJointMovJ > {
  static const char* value()
  {
    return "03967d766f807d795f6e85af35f413a1";
  }

  static const char* value(const ::dobot_bringup::RelJointMovJ&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::RelJointMovJ > {
  static const char* value()
  {
    return "dobot_bringup/RelJointMovJ";
  }

  static const char* value(const ::dobot_bringup::RelJointMovJ&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::RelJointMovJRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::RelJointMovJ >
template<>
struct MD5Sum< ::dobot_bringup::RelJointMovJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelJointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::RelJointMovJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelJointMovJRequest> should match
// service_traits::DataType< ::dobot_bringup::RelJointMovJ >
template<>
struct DataType< ::dobot_bringup::RelJointMovJRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelJointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::RelJointMovJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::RelJointMovJResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::RelJointMovJ >
template<>
struct MD5Sum< ::dobot_bringup::RelJointMovJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelJointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::RelJointMovJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelJointMovJResponse> should match
// service_traits::DataType< ::dobot_bringup::RelJointMovJ >
template<>
struct DataType< ::dobot_bringup::RelJointMovJResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelJointMovJ >::value();
  }
  static const char* value(const ::dobot_bringup::RelJointMovJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_RELJOINTMOVJ_H
