// Generated by gencpp from file dobot_bringup/RelMovLTool.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_RELMOVLTOOL_H
#define DOBOT_BRINGUP_MESSAGE_RELMOVLTOOL_H

#include <ros/service_traits.h>


#include <dobot_bringup/RelMovLToolRequest.h>
#include <dobot_bringup/RelMovLToolResponse.h>


namespace dobot_bringup
{

struct RelMovLTool
{

typedef RelMovLToolRequest Request;
typedef RelMovLToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelMovLTool
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::RelMovLTool > {
  static const char* value()
  {
    return "cce5d7b80bc419b447b80cc47eb8fc50";
  }

  static const char* value(const ::dobot_bringup::RelMovLTool&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::RelMovLTool > {
  static const char* value()
  {
    return "dobot_bringup/RelMovLTool";
  }

  static const char* value(const ::dobot_bringup::RelMovLTool&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::RelMovLToolRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovLTool >
template<>
struct MD5Sum< ::dobot_bringup::RelMovLToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovLToolRequest> should match
// service_traits::DataType< ::dobot_bringup::RelMovLTool >
template<>
struct DataType< ::dobot_bringup::RelMovLToolRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::RelMovLToolResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovLTool >
template<>
struct MD5Sum< ::dobot_bringup::RelMovLToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovLToolResponse> should match
// service_traits::DataType< ::dobot_bringup::RelMovLTool >
template<>
struct DataType< ::dobot_bringup::RelMovLToolResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovLTool >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_RELMOVLTOOL_H
