// Generated by gencpp from file dobot_bringup/RobotMode.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_ROBOTMODE_H
#define DOBOT_BRINGUP_MESSAGE_ROBOTMODE_H

#include <ros/service_traits.h>


#include <dobot_bringup/RobotModeRequest.h>
#include <dobot_bringup/RobotModeResponse.h>


namespace dobot_bringup
{

struct RobotMode
{

typedef RobotModeRequest Request;
typedef RobotModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotMode
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::RobotMode > {
  static const char* value()
  {
    return "6c9e8010af56fb13be385391b43d24ba";
  }

  static const char* value(const ::dobot_bringup::RobotMode&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::RobotMode > {
  static const char* value()
  {
    return "dobot_bringup/RobotMode";
  }

  static const char* value(const ::dobot_bringup::RobotMode&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::RobotModeRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::RobotMode >
template<>
struct MD5Sum< ::dobot_bringup::RobotModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RobotMode >::value();
  }
  static const char* value(const ::dobot_bringup::RobotModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RobotModeRequest> should match
// service_traits::DataType< ::dobot_bringup::RobotMode >
template<>
struct DataType< ::dobot_bringup::RobotModeRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RobotMode >::value();
  }
  static const char* value(const ::dobot_bringup::RobotModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::RobotModeResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::RobotMode >
template<>
struct MD5Sum< ::dobot_bringup::RobotModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RobotMode >::value();
  }
  static const char* value(const ::dobot_bringup::RobotModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RobotModeResponse> should match
// service_traits::DataType< ::dobot_bringup::RobotMode >
template<>
struct DataType< ::dobot_bringup::RobotModeResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RobotMode >::value();
  }
  static const char* value(const ::dobot_bringup::RobotModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_ROBOTMODE_H
