// Generated by gencpp from file dobot_bringup/SetCoilsRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_SETCOILSREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_SETCOILSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct SetCoilsRequest_
{
  typedef SetCoilsRequest_<ContainerAllocator> Type;

  SetCoilsRequest_()
    : index(0)
    , addr(0)
    , count(0)
    , valTab()  {
    }
  SetCoilsRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , addr(0)
    , count(0)
    , valTab(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _addr_type;
  _addr_type addr;

   typedef int32_t _count_type;
  _count_type count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _valTab_type;
  _valTab_type valTab;





  typedef boost::shared_ptr< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCoilsRequest_

typedef ::dobot_bringup::SetCoilsRequest_<std::allocator<void> > SetCoilsRequest;

typedef boost::shared_ptr< ::dobot_bringup::SetCoilsRequest > SetCoilsRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::SetCoilsRequest const> SetCoilsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.addr == rhs.addr &&
    lhs.count == rhs.count &&
    lhs.valTab == rhs.valTab;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3c85c95dc4d516f27a5345858b1bf63";
  }

  static const char* value(const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3c85c95dc4d516fULL;
  static const uint64_t static_value2 = 0x27a5345858b1bf63ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/SetCoilsRequest";
  }

  static const char* value(const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"int32 addr\n"
"int32 count\n"
"string valTab\n"
;
  }

  static const char* value(const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.addr);
      stream.next(m.count);
      stream.next(m.valTab);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCoilsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::SetCoilsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::SetCoilsRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "addr: ";
    Printer<int32_t>::stream(s, indent + "  ", v.addr);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "valTab: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.valTab);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_SETCOILSREQUEST_H
