// Generated by gencpp from file dobot_bringup/SpeedJ.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_SPEEDJ_H
#define DOBOT_BRINGUP_MESSAGE_SPEEDJ_H

#include <ros/service_traits.h>


#include <dobot_bringup/SpeedJRequest.h>
#include <dobot_bringup/SpeedJResponse.h>


namespace dobot_bringup
{

struct SpeedJ
{

typedef SpeedJRequest Request;
typedef SpeedJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeedJ
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::SpeedJ > {
  static const char* value()
  {
    return "941d9ecd0f5402311261de883bef5059";
  }

  static const char* value(const ::dobot_bringup::SpeedJ&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::SpeedJ > {
  static const char* value()
  {
    return "dobot_bringup/SpeedJ";
  }

  static const char* value(const ::dobot_bringup::SpeedJ&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::SpeedJRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::SpeedJ >
template<>
struct MD5Sum< ::dobot_bringup::SpeedJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::SpeedJ >::value();
  }
  static const char* value(const ::dobot_bringup::SpeedJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::SpeedJRequest> should match
// service_traits::DataType< ::dobot_bringup::SpeedJ >
template<>
struct DataType< ::dobot_bringup::SpeedJRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::SpeedJ >::value();
  }
  static const char* value(const ::dobot_bringup::SpeedJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::SpeedJResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::SpeedJ >
template<>
struct MD5Sum< ::dobot_bringup::SpeedJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::SpeedJ >::value();
  }
  static const char* value(const ::dobot_bringup::SpeedJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::SpeedJResponse> should match
// service_traits::DataType< ::dobot_bringup::SpeedJ >
template<>
struct DataType< ::dobot_bringup::SpeedJResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::SpeedJ >::value();
  }
  static const char* value(const ::dobot_bringup::SpeedJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_SPEEDJ_H
