// Generated by gencpp from file dobot_bringup/Tool.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_TOOL_H
#define DOBOT_BRINGUP_MESSAGE_TOOL_H

#include <ros/service_traits.h>


#include <dobot_bringup/ToolRequest.h>
#include <dobot_bringup/ToolResponse.h>


namespace dobot_bringup
{

struct Tool
{

typedef ToolRequest Request;
typedef ToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tool
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::Tool > {
  static const char* value()
  {
    return "6d753c0adbdd6c06a6eb5c36aec96b0c";
  }

  static const char* value(const ::dobot_bringup::Tool&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::Tool > {
  static const char* value()
  {
    return "dobot_bringup/Tool";
  }

  static const char* value(const ::dobot_bringup::Tool&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::ToolRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::Tool >
template<>
struct MD5Sum< ::dobot_bringup::ToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::Tool >::value();
  }
  static const char* value(const ::dobot_bringup::ToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ToolRequest> should match
// service_traits::DataType< ::dobot_bringup::Tool >
template<>
struct DataType< ::dobot_bringup::ToolRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::Tool >::value();
  }
  static const char* value(const ::dobot_bringup::ToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::ToolResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::Tool >
template<>
struct MD5Sum< ::dobot_bringup::ToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::Tool >::value();
  }
  static const char* value(const ::dobot_bringup::ToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ToolResponse> should match
// service_traits::DataType< ::dobot_bringup::Tool >
template<>
struct DataType< ::dobot_bringup::ToolResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::Tool >::value();
  }
  static const char* value(const ::dobot_bringup::ToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_TOOL_H
