<?xml version="1.0" encoding="utf-8"?>
<robot name="nova5_robot" xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:include filename="camera.xacro"/>
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />

  <!-- SET CAMERA POSITION AND FOV OFFSET HERE -->
  <!-- <xacro:property name="camera_position" value="0.011150000000000002 0 0.0145"/> -->
  <xacro:property name="camera_position" value="0.011150000000000002 0 0"/>
  <xacro:property name="camera_orientation" value="0 0 0"/>
  <xacro:property name="fov_offset" value="0.00465 0 0"/>

   <xacro:property name="platform_type" value="panther"/>
   <!-- PLATFORM TYPES
   panther
   hunter
   -->

  <link name="world"/>
  <joint
    name="world_joint"
    type="fixed">
    <origin xyz="0 0 0.16" rpy="0 0 0"/>
    <parent
      link="world" />
    <child
      link="mobile_platform_link" />
  </joint>
  <xacro:property name="r" value="0.08" />
  <xacro:property name="h" value="0.20" />
  <xacro:property name="limit" value="40000"/>
  <material name="aluminum">
      <color rgba="0.5 0.5 0.5 1" />
  </material>
  <material name="plastic">
      <color rgba="0.1 0.1 0.1 1" />
  </material>

  <link name="mobile_platform_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <mesh
          filename="package://dobot_description/meshes/nova5/${platform_type}.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0.04" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.00308109148952278"
        ixy="-4.0369958400766E-08"
        ixz="5.2607663395944E-07"
        iyy="0.00309758743296662"
        iyz="-6.37484696538659E-09"
        izz="0.00232835367593981" />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="mobile_platform_link">
    <material>Gazebo/Grey</material>
    <dampingFactor>0.05</dampingFactor>
    <kp>1000000</kp>
    <kd>1.0</kd>
    <mu1>100.0</mu1>
    <mu2>100.0</mu2>
    <minDepth>0.001</minDepth>
  </gazebo>

  <joint
    name="robot_joint"
    type="fixed">
    <origin
      xyz="0 0 0.5"
      rpy="0 0 0" />
    <parent
      link="mobile_platform_link" />
    <child
      link="base_link" />
  </joint>

  <link
    name="base_link">
    <inertial>
      <origin
        xyz="6.56698714338847E-06 2.73052159273858E-06 0.0698223124889706"
        rpy="0 0 0" />
      <mass
        value="1.3106443915978" />
      <inertia
        ixx="0.00308109148952278"
        ixy="-4.0369958400766E-08"
        ixz="5.2607663395944E-07"
        iyy="0.00309758743296662"
        iyz="-6.37484696538659E-09"
        izz="0.00232835367593981" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/base_link.STL" />
      </geometry>
    </collision>
  </link>
  <link
    name="Link1">
    <inertial>
      <origin
        xyz="9.18642704220017E-06 -0.021770784235076 -0.0261833991373472"
        rpy="0 0 0" />
      <mass
        value="1.08090940330212" />
      <inertia
        ixx="0.00265963193119309"
        ixy="1.85196348994647E-07"
        ixz="-3.27720040926316E-07"
        iyy="0.00247342331575097"
        iyz="0.000661331129337329"
        izz="0.00164737186015792" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint1"
    type="revolute">
    <origin
      xyz="0 0 0.240000000000178"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="Link1" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.28"
      upper="6.28"
      effort="${limit}"
      velocity="${limit}" />
  </joint>
  <link
    name="Link2">
    <inertial>
      <origin
        xyz="-0.19933810729628 -0.00696463483971123 0.109208661556353"
        rpy="0 0 0" />
      <mass
        value="2.54585370113969" />
      <inertia
        ixx="0.00285193319464959"
        ixy="-0.00212784400881843"
        ixz="-0.00109906472415148"
        iyy="0.0636767872390402"
        iyz="-3.83872488712299E-05"
        izz="0.0643005121111712" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link2.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint2"
    type="revolute">
    <origin
      xyz="0 0 0"
      rpy="-1.57080287682252 1.53586622836832 3.14159265358979" />
    <parent
      link="Link1" />
    <child
      link="Link2" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-3.14"
      upper="3.14"
      effort="${limit}"
      velocity="${limit}" />
  </joint>
  <link
    name="Link3">
    <inertial>
      <origin
        xyz="-0.152357289724291 -0.0053571688729055 0.0198991511385547"
        rpy="0 0 0" />
      <mass
        value="1.40745649848125" />
      <inertia
        ixx="0.00100801309674517"
        ixy="-0.00077546601599374"
        ixz="4.43267247578911E-05"
        iyy="0.0231741793950995"
        iyz="1.31338010910521E-06"
        izz="0.02359962285525" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link3.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint3"
    type="revolute">
    <origin
      xyz="-0.399756009268664 -0.0139690033141953 0"
      rpy="0 0 0" />
    <parent
      link="Link2" />
    <child
      link="Link3" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.79"
      upper="2.79"
      effort="${limit}"
      velocity="${limit}" />
  </joint>
  <link
    name="Link4">
    <inertial>
      <origin
        xyz="-6.37112093033953E-06 -0.0227590499933018 -0.0202381689250349"
        rpy="0 0 0" />
      <mass
        value="0.439666284541787" />
      <inertia
        ixx="0.000634738696193051"
        ixy="1.33529119545257E-08"
        ixz="2.91412587537874E-08"
        iyy="0.00045014395177395"
        iyz="0.000210919680187578"
        izz="0.000480311391216564" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link4.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link4.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint4"
    type="revolute">
    <origin
      xyz="-0.329798707647103 -0.0115244277211674 0.134999532858734"
      rpy="0 0 -1.53586622840712" />
    <parent
      link="Link3" />
    <child
      link="Link4" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.28"
      upper="6.28"
      effort="${limit}"
      velocity="${limit}" />
  </joint>
  <link
    name="Link5">
    <inertial>
      <origin
        xyz="-1.27925890990664E-06 0.00190911597991161 -0.0076111865696753"
        rpy="0 0 0" />
      <mass
        value="0.574835130260071" />
      <inertia
        ixx="0.000663176880523558"
        ixy="1.30179448329138E-08"
        ixz="1.22670358756949E-08"
        iyy="0.000397520749670404"
        iyz="-0.00012026389265228"
        izz="0.000641156648195347" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link5.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link5.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint5"
    type="revolute">
    <origin
      xyz="0 -0.12 0"
      rpy="1.5708 0 0" />
    <parent
      link="Link4" />
    <child
      link="Link5" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.28"
      upper="6.28"
      effort="${limit}"
      velocity="${limit}" />
  </joint>
  <link
    name="Link6">
    <inertial>
      <origin
        xyz="1.5476173180832E-06 0.000151598525687691 -0.0194592287865595"
        rpy="0 0 0" />
      <mass
        value="0.129679940383395" />
      <inertia
        ixx="5.02803124561327E-05"
        ixy="6.27222112028976E-11"
        ixz="3.5128727780266E-12"
        iyy="5.05400746124736E-05"
        iyz="5.0343678900728E-08"
        izz="7.7863015024978E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link6.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.752941176470588 0.752941176470588 0.752941176470588 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dobot_description/meshes/nova5/Link6.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint6"
    type="revolute">
    <origin
      xyz="0 0.088328 0"
      rpy="-1.5708 0 0" />
    <parent
      link="Link5" />
    <child
      link="Link6" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.28"
      upper="6.28"
      effort="${limit}"
      velocity="${limit}" />
  </joint>

  <link
    name="base_link_gripper">
    <inertial>
      <origin
        xyz="-3.9257E-06 -0.00027208 0.037806"
        rpy="0 0 0" />
      <mass
        value="0.34365" />
      <inertia
        ixx="0.00036805"
        ixy="-7.2868E-08"
        ixz="-5.0168E-08"
        iyy="0.0003341"
        iyz="-2.6462E-06"
        izz="0.00022294" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/base_link.STL" />
      </geometry>
    </collision>
  </link>

  <link name="camera_bottom_screw_frame" />

  <!-- <joint name="camera_joint" type="fixed">
      <origin rpy="0 -1.57 0" xyz="0.065 0 0" />
      <parent link="base_link_gripper" />
      <child link="camera_bottom_screw_frame" />
  </joint> -->
  <joint name="camera_joint" type="fixed">
      <origin rpy="0 0 -1.57" xyz="0 -0.360 0.02" />
      <parent link="base_link" />
      <child link="camera_bottom_screw_frame" />
  </joint>

  <link name="camera_link">
      <visual>
          <!-- the mesh origin is at front plate in between the two infrared camera axes -->
          <!-- <origin xyz="${d455_zero_depth_to_glass-d455_cam_depth/2} ${-d455_cam_depth_py} 0" rpy="0 0 0"/> -->
          <origin rpy="1.5707963267948966 0 1.5707963267948966" xyz="${fov_offset}" />
          <geometry>
              <!-- <box size="${d455_cam_depth} ${d455_cam_width} ${d455_cam_height}"/> -->
              <mesh filename="package://realsense2_description/meshes/d435.stl" scale="0.001 0.001 0.001"/>
          </geometry>
          <material name="aluminum" />
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="-0.00845 -0.0475 0" />
          <geometry>
              <box size="0.026 0.124 0.029" />
          </geometry>
      </collision>
      <inertial>
          <!-- The following are not reliable values, and should not be used for modeling -->
          <mass value="0.072" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
  </link>

 
   <!-- Change camera position-->
  <!-- <joint name="camera_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${camera_position}" />
    <parent link="camera_bottom_screw_frame" />
    <child link="camera_link" />
  </joint> -->

    
  <!-- <xacro:sensor_d435 name="camera" topics_ns="camera" parent="base_link_gripper" publish_pointcloud="true">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:sensor_d435>   -->

  <joint name="camera_link_joint" type="fixed">
    <origin rpy="${camera_orientation}" xyz="${camera_position}" />
    <parent link="camera_bottom_screw_frame" />
    <child link="camera_link" />
  </joint>

  <xacro:sensor_d435 name="camera" topics_ns="camera" parent="base_link" publish_pointcloud="true">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:sensor_d435>  


  <link
    name="finger1_link">
    <inertial>
      <origin
        xyz="0.0030491 -0.0066024 0.0064209"
        rpy="0 0 0" />
      <mass
        value="0.014278" />
      <inertia
        ixx="1.7567E-06"
        ixy="-5.7832E-08"
        ixz="2.6803E-08"
        iyy="2.3034E-06"
        iyz="2.2145E-07"
        izz="1.3354E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/finger1_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/finger1_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger1_joint"
    type="prismatic">
    <origin
      xyz="0.0132 0.0265 0.093"
      rpy="0 0 -1.5708" />
    <parent
      link="base_link_gripper" />
    <child
      link="finger1_link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-0.09"
      upper="0.025"
      effort="${limit}"
      velocity="${limit}" />
    <dynamics damping="0" friction="0"/>
  </joint>
  <link
    name="finger2_link">
    <inertial>
      <origin
        xyz="0.0030491 -0.0066024 0.0064209"
        rpy="0 0 0" />
      <mass
        value="0.014278" />
      <inertia
        ixx="1.7567E-06"
        ixy="-5.7832E-08"
        ixz="2.6803E-08"
        iyy="2.3034E-06"
        iyz="2.2145E-07"
        izz="1.3354E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/finger2_Link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://dh_pgc140_urdf/meshes/finger2_Link.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="finger2_joint"
    type="prismatic">
    <origin
      xyz="-0.0132 -0.0265 0.093"
      rpy="0 0 1.5708" />
    <parent
      link="base_link_gripper" />
    <child
      link="finger2_link" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-0.09"
      upper="0.025"
      effort="${limit}"
      velocity="${limit}" />
    <mimic
      joint="finger1_joint"
      multiplier="1"
      offset="0" />
      <dynamics damping="0" friction="0"/>
  </joint>

  <joint name="gripper_joint" type="fixed">
    <parent link="Link6"/>
    <child link="base_link_gripper"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <!-- create a virtual fixed joint for having the point of the picking of the gripper-->

 <link name="picking_point" />
 <joint name="picking_joint" type="fixed">
    <parent link="Link6"/>
    <child link="picking_point"/>
    <origin xyz="0.0 0.0 0.12" rpy="0 0 0"/>
  </joint>

  
 <xacro:macro name="robot_transmission" params="joint_name">
    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
 </xacro:macro>

 <xacro:robot_transmission joint_name="joint1"/>
 <xacro:robot_transmission joint_name="joint2"/>
 <xacro:robot_transmission joint_name="joint3"/>
 <xacro:robot_transmission joint_name="joint4"/>
 <xacro:robot_transmission joint_name="joint5"/>
 <xacro:robot_transmission joint_name="joint6"/>
 <xacro:robot_transmission joint_name="finger1_joint"/>
 <xacro:robot_transmission joint_name="finger2_joint"/>
 <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/nova5_robot</robotNamespace>
    </plugin>
 </gazebo>

<gazebo>
  <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
    <arm>
        <arm_name>nova5_robot</arm_name>
        <palm_link>Link6</palm_link>
        <gripper_link>finger1_link</gripper_link>
        <gripper_link>finger2_link</gripper_link>
    </arm>
    <forces_angle_tolerance>90</forces_angle_tolerance>
    <update_rate>4</update_rate>
    <grip_count_threshold>1</grip_count_threshold>
    <max_grip_count>2</max_grip_count>
    <release_tolerance>0.01</release_tolerance>
    <disable_collisions_on_attach>true</disable_collisions_on_attach>
    <contact_topic>__default_topic__</contact_topic>
  </plugin>
</gazebo>


    <!-- Added Gazebo plugin for grippers -->
    <xacro:macro name="mimic_joint_plugin_gazebo" params="parent_joint mimic_joint has_pid:=false multiplier:=1.0 offset:=0 sensitiveness:=0.0 max_effort:=200 robot_namespace:='/nova5_robot'">
            <gazebo>
                <plugin name="${mimic_joint}_mimic_joint_plugin" filename="libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so">
                    <joint>${parent_joint}</joint>
                    <mimicJoint>${mimic_joint}</mimicJoint>
                    <xacro:if value="${has_pid}">
                        <hasPID />
                    </xacro:if>
                    <multiplier>${multiplier}</multiplier>
                    <offset>${offset}</offset>
                    <sensitiveness>${sensitiveness}</sensitiveness>
                    <maxEffort>${max_effort}</maxEffort>
                    <xacro:unless value="${robot_namespace == '/nova5_robot'}">
                        <robotNamespace>($robot_namespace)</robotNamespace>
                    </xacro:unless>
                </plugin>
            </gazebo>
    </xacro:macro>
        

    <xacro:mimic_joint_plugin_gazebo  parent_joint="finger1_link" mimic_joint="finger2_link" 
                                            has_pid="false" multiplier="1.0" max_effort="200" />

</robot>
