(cl:in-package dobot_bringup-srv)
(cl:export '(COUNT-VAL
          COUNT
          X1-VAL
          X1
          Y1-VAL
          Y1
          Z1-VAL
          Z1
          A1-VAL
          A1
          B1-VAL
          B1
          C1-VAL
          C1
          X2-VAL
          X2
          Y2-VAL
          Y2
          Z2-VAL
          Z2
          A2-VAL
          A2
          B2-VAL
          B2
          C2-VAL
          C2
          PARAMVALUE-VAL
          PARAMVALUE
          RES-VAL
          RES
))