// Generated by gencpp from file dobot_bringup/AO.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_AO_H
#define DOBOT_BRINGUP_MESSAGE_AO_H

#include <ros/service_traits.h>


#include <dobot_bringup/AORequest.h>
#include <dobot_bringup/AOResponse.h>


namespace dobot_bringup
{

struct AO
{

typedef AORequest Request;
typedef AOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AO
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::AO > {
  static const char* value()
  {
    return "096263ad689c1ece47cec4376ad5d3b5";
  }

  static const char* value(const ::dobot_bringup::AO&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::AO > {
  static const char* value()
  {
    return "dobot_bringup/AO";
  }

  static const char* value(const ::dobot_bringup::AO&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::AORequest> should match
// service_traits::MD5Sum< ::dobot_bringup::AO >
template<>
struct MD5Sum< ::dobot_bringup::AORequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::AO >::value();
  }
  static const char* value(const ::dobot_bringup::AORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::AORequest> should match
// service_traits::DataType< ::dobot_bringup::AO >
template<>
struct DataType< ::dobot_bringup::AORequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::AO >::value();
  }
  static const char* value(const ::dobot_bringup::AORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::AOResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::AO >
template<>
struct MD5Sum< ::dobot_bringup::AOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::AO >::value();
  }
  static const char* value(const ::dobot_bringup::AOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::AOResponse> should match
// service_traits::DataType< ::dobot_bringup::AO >
template<>
struct DataType< ::dobot_bringup::AOResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::AO >::value();
  }
  static const char* value(const ::dobot_bringup::AOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_AO_H
