// Generated by gencpp from file dobot_bringup/ArchRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_ARCHREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_ARCHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct ArchRequest_
{
  typedef ArchRequest_<ContainerAllocator> Type;

  ArchRequest_()
    : index(0)
    , cpValue()  {
    }
  ArchRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , cpValue(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _cpValue_type;
  _cpValue_type cpValue;





  typedef boost::shared_ptr< ::dobot_bringup::ArchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::ArchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArchRequest_

typedef ::dobot_bringup::ArchRequest_<std::allocator<void> > ArchRequest;

typedef boost::shared_ptr< ::dobot_bringup::ArchRequest > ArchRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::ArchRequest const> ArchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::ArchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::ArchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::ArchRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::ArchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.cpValue == rhs.cpValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::ArchRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::ArchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::ArchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::ArchRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::ArchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a13bec9591f94e0243ff85534dbde425";
  }

  static const char* value(const ::dobot_bringup::ArchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa13bec9591f94e02ULL;
  static const uint64_t static_value2 = 0x43ff85534dbde425ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/ArchRequest";
  }

  static const char* value(const ::dobot_bringup::ArchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# index --> 0 - 9\n"
"\n"
"int32 index\n"
"string[] cpValue\n"
;
  }

  static const char* value(const ::dobot_bringup::ArchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.cpValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::ArchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::ArchRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "cpValue[]" << std::endl;
    for (size_t i = 0; i < v.cpValue.size(); ++i)
    {
      s << indent << "  cpValue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cpValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_ARCHREQUEST_H
