// Generated by gencpp from file dobot_bringup/BrakeControl.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_BRAKECONTROL_H
#define DOBOT_BRINGUP_MESSAGE_BRAKECONTROL_H

#include <ros/service_traits.h>


#include <dobot_bringup/BrakeControlRequest.h>
#include <dobot_bringup/BrakeControlResponse.h>


namespace dobot_bringup
{

struct BrakeControl
{

typedef BrakeControlRequest Request;
typedef BrakeControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BrakeControl
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::BrakeControl > {
  static const char* value()
  {
    return "2600ab19caac21b4314a6daf413b16b7";
  }

  static const char* value(const ::dobot_bringup::BrakeControl&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::BrakeControl > {
  static const char* value()
  {
    return "dobot_bringup/BrakeControl";
  }

  static const char* value(const ::dobot_bringup::BrakeControl&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::BrakeControlRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::BrakeControl >
template<>
struct MD5Sum< ::dobot_bringup::BrakeControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::BrakeControl >::value();
  }
  static const char* value(const ::dobot_bringup::BrakeControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::BrakeControlRequest> should match
// service_traits::DataType< ::dobot_bringup::BrakeControl >
template<>
struct DataType< ::dobot_bringup::BrakeControlRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::BrakeControl >::value();
  }
  static const char* value(const ::dobot_bringup::BrakeControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::BrakeControlResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::BrakeControl >
template<>
struct MD5Sum< ::dobot_bringup::BrakeControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::BrakeControl >::value();
  }
  static const char* value(const ::dobot_bringup::BrakeControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::BrakeControlResponse> should match
// service_traits::DataType< ::dobot_bringup::BrakeControl >
template<>
struct DataType< ::dobot_bringup::BrakeControlResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::BrakeControl >::value();
  }
  static const char* value(const ::dobot_bringup::BrakeControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_BRAKECONTROL_H
