// Generated by gencpp from file dobot_bringup/DIGroupRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_DIGROUPREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_DIGROUPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct DIGroupRequest_
{
  typedef DIGroupRequest_<ContainerAllocator> Type;

  DIGroupRequest_()
    : args()  {
    }
  DIGroupRequest_(const ContainerAllocator& _alloc)
    : args(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _args_type;
  _args_type args;





  typedef boost::shared_ptr< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DIGroupRequest_

typedef ::dobot_bringup::DIGroupRequest_<std::allocator<void> > DIGroupRequest;

typedef boost::shared_ptr< ::dobot_bringup::DIGroupRequest > DIGroupRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::DIGroupRequest const> DIGroupRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::DIGroupRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::DIGroupRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::DIGroupRequest_<ContainerAllocator2> & rhs)
{
  return lhs.args == rhs.args;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::DIGroupRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::DIGroupRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c499e781e7abae5a538ee7145140c1d0";
  }

  static const char* value(const ::dobot_bringup::DIGroupRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc499e781e7abae5aULL;
  static const uint64_t static_value2 = 0x538ee7145140c1d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/DIGroupRequest";
  }

  static const char* value(const ::dobot_bringup::DIGroupRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] args\n"
"\n"
;
  }

  static const char* value(const ::dobot_bringup::DIGroupRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.args);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DIGroupRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::DIGroupRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::DIGroupRequest_<ContainerAllocator>& v)
  {
    s << indent << "args[]" << std::endl;
    for (size_t i = 0; i < v.args.size(); ++i)
    {
      s << indent << "  args[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.args[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_DIGROUPREQUEST_H
