// Generated by gencpp from file dobot_bringup/GetAngle.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_GETANGLE_H
#define DOBOT_BRINGUP_MESSAGE_GETANGLE_H

#include <ros/service_traits.h>


#include <dobot_bringup/GetAngleRequest.h>
#include <dobot_bringup/GetAngleResponse.h>


namespace dobot_bringup
{

struct GetAngle
{

typedef GetAngleRequest Request;
typedef GetAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAngle
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::GetAngle > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::dobot_bringup::GetAngle&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::GetAngle > {
  static const char* value()
  {
    return "dobot_bringup/GetAngle";
  }

  static const char* value(const ::dobot_bringup::GetAngle&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::GetAngleRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::GetAngle >
template<>
struct MD5Sum< ::dobot_bringup::GetAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetAngle >::value();
  }
  static const char* value(const ::dobot_bringup::GetAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetAngleRequest> should match
// service_traits::DataType< ::dobot_bringup::GetAngle >
template<>
struct DataType< ::dobot_bringup::GetAngleRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetAngle >::value();
  }
  static const char* value(const ::dobot_bringup::GetAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::GetAngleResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::GetAngle >
template<>
struct MD5Sum< ::dobot_bringup::GetAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetAngle >::value();
  }
  static const char* value(const ::dobot_bringup::GetAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetAngleResponse> should match
// service_traits::DataType< ::dobot_bringup::GetAngle >
template<>
struct DataType< ::dobot_bringup::GetAngleResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetAngle >::value();
  }
  static const char* value(const ::dobot_bringup::GetAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_GETANGLE_H
