// Generated by gencpp from file dobot_bringup/GetInRegsRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_GETINREGSREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_GETINREGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct GetInRegsRequest_
{
  typedef GetInRegsRequest_<ContainerAllocator> Type;

  GetInRegsRequest_()
    : index(0)
    , addr(0)
    , count(0)
    , valType()  {
    }
  GetInRegsRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , addr(0)
    , count(0)
    , valType(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _addr_type;
  _addr_type addr;

   typedef int32_t _count_type;
  _count_type count;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _valType_type;
  _valType_type valType;





  typedef boost::shared_ptr< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetInRegsRequest_

typedef ::dobot_bringup::GetInRegsRequest_<std::allocator<void> > GetInRegsRequest;

typedef boost::shared_ptr< ::dobot_bringup::GetInRegsRequest > GetInRegsRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::GetInRegsRequest const> GetInRegsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.addr == rhs.addr &&
    lhs.count == rhs.count &&
    lhs.valType == rhs.valType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6dc24058408856cd315a278f3b0abec";
  }

  static const char* value(const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6dc24058408856cULL;
  static const uint64_t static_value2 = 0xd315a278f3b0abecULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/GetInRegsRequest";
  }

  static const char* value(const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"int32 addr\n"
"int32 count\n"
"string[] valType\n"
;
  }

  static const char* value(const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.addr);
      stream.next(m.count);
      stream.next(m.valType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInRegsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::GetInRegsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::GetInRegsRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "addr: ";
    Printer<int32_t>::stream(s, indent + "  ", v.addr);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "valType[]" << std::endl;
    for (size_t i = 0; i < v.valType.size(); ++i)
    {
      s << indent << "  valType[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.valType[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_GETINREGSREQUEST_H
