// Generated by gencpp from file dobot_bringup/GetTerminal485.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_GETTERMINAL485_H
#define DOBOT_BRINGUP_MESSAGE_GETTERMINAL485_H

#include <ros/service_traits.h>


#include <dobot_bringup/GetTerminal485Request.h>
#include <dobot_bringup/GetTerminal485Response.h>


namespace dobot_bringup
{

struct GetTerminal485
{

typedef GetTerminal485Request Request;
typedef GetTerminal485Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTerminal485
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::GetTerminal485 > {
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::dobot_bringup::GetTerminal485&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::GetTerminal485 > {
  static const char* value()
  {
    return "dobot_bringup/GetTerminal485";
  }

  static const char* value(const ::dobot_bringup::GetTerminal485&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::GetTerminal485Request> should match
// service_traits::MD5Sum< ::dobot_bringup::GetTerminal485 >
template<>
struct MD5Sum< ::dobot_bringup::GetTerminal485Request>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetTerminal485 >::value();
  }
  static const char* value(const ::dobot_bringup::GetTerminal485Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetTerminal485Request> should match
// service_traits::DataType< ::dobot_bringup::GetTerminal485 >
template<>
struct DataType< ::dobot_bringup::GetTerminal485Request>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetTerminal485 >::value();
  }
  static const char* value(const ::dobot_bringup::GetTerminal485Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::GetTerminal485Response> should match
// service_traits::MD5Sum< ::dobot_bringup::GetTerminal485 >
template<>
struct MD5Sum< ::dobot_bringup::GetTerminal485Response>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::GetTerminal485 >::value();
  }
  static const char* value(const ::dobot_bringup::GetTerminal485Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::GetTerminal485Response> should match
// service_traits::DataType< ::dobot_bringup::GetTerminal485 >
template<>
struct DataType< ::dobot_bringup::GetTerminal485Response>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::GetTerminal485 >::value();
  }
  static const char* value(const ::dobot_bringup::GetTerminal485Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_GETTERMINAL485_H
