// Generated by gencpp from file dobot_bringup/InverseSolutionRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_INVERSESOLUTIONREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_INVERSESOLUTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct InverseSolutionRequest_
{
  typedef InverseSolutionRequest_<ContainerAllocator> Type;

  InverseSolutionRequest_()
    : offset1(0.0)
    , offset2(0.0)
    , offset3(0.0)
    , offset4(0.0)
    , offset5(0.0)
    , offset6(0.0)
    , user(0)
    , tool(0)
    , isJointNear(0)
    , JointNear()  {
    }
  InverseSolutionRequest_(const ContainerAllocator& _alloc)
    : offset1(0.0)
    , offset2(0.0)
    , offset3(0.0)
    , offset4(0.0)
    , offset5(0.0)
    , offset6(0.0)
    , user(0)
    , tool(0)
    , isJointNear(0)
    , JointNear(_alloc)  {
  (void)_alloc;
    }



   typedef double _offset1_type;
  _offset1_type offset1;

   typedef double _offset2_type;
  _offset2_type offset2;

   typedef double _offset3_type;
  _offset3_type offset3;

   typedef double _offset4_type;
  _offset4_type offset4;

   typedef double _offset5_type;
  _offset5_type offset5;

   typedef double _offset6_type;
  _offset6_type offset6;

   typedef int32_t _user_type;
  _user_type user;

   typedef int32_t _tool_type;
  _tool_type tool;

   typedef int32_t _isJointNear_type;
  _isJointNear_type isJointNear;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _JointNear_type;
  _JointNear_type JointNear;





  typedef boost::shared_ptr< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InverseSolutionRequest_

typedef ::dobot_bringup::InverseSolutionRequest_<std::allocator<void> > InverseSolutionRequest;

typedef boost::shared_ptr< ::dobot_bringup::InverseSolutionRequest > InverseSolutionRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::InverseSolutionRequest const> InverseSolutionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offset1 == rhs.offset1 &&
    lhs.offset2 == rhs.offset2 &&
    lhs.offset3 == rhs.offset3 &&
    lhs.offset4 == rhs.offset4 &&
    lhs.offset5 == rhs.offset5 &&
    lhs.offset6 == rhs.offset6 &&
    lhs.user == rhs.user &&
    lhs.tool == rhs.tool &&
    lhs.isJointNear == rhs.isJointNear &&
    lhs.JointNear == rhs.JointNear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a56434a738fb69f7e97a6dc9a3bb7f8d";
  }

  static const char* value(const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa56434a738fb69f7ULL;
  static const uint64_t static_value2 = 0xe97a6dc9a3bb7f8dULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/InverseSolutionRequest";
  }

  static const char* value(const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 offset1\n"
"float64 offset2\n"
"float64 offset3\n"
"float64 offset4\n"
"float64 offset5\n"
"float64 offset6\n"
"int32 user\n"
"int32 tool\n"
"int32 isJointNear\n"
"string JointNear\n"
;
  }

  static const char* value(const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset1);
      stream.next(m.offset2);
      stream.next(m.offset3);
      stream.next(m.offset4);
      stream.next(m.offset5);
      stream.next(m.offset6);
      stream.next(m.user);
      stream.next(m.tool);
      stream.next(m.isJointNear);
      stream.next(m.JointNear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InverseSolutionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::InverseSolutionRequest_<ContainerAllocator>& v)
  {
    s << indent << "offset1: ";
    Printer<double>::stream(s, indent + "  ", v.offset1);
    s << indent << "offset2: ";
    Printer<double>::stream(s, indent + "  ", v.offset2);
    s << indent << "offset3: ";
    Printer<double>::stream(s, indent + "  ", v.offset3);
    s << indent << "offset4: ";
    Printer<double>::stream(s, indent + "  ", v.offset4);
    s << indent << "offset5: ";
    Printer<double>::stream(s, indent + "  ", v.offset5);
    s << indent << "offset6: ";
    Printer<double>::stream(s, indent + "  ", v.offset6);
    s << indent << "user: ";
    Printer<int32_t>::stream(s, indent + "  ", v.user);
    s << indent << "tool: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tool);
    s << indent << "isJointNear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isJointNear);
    s << indent << "JointNear: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.JointNear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_INVERSESOLUTIONREQUEST_H
