// Generated by gencpp from file dobot_bringup/InverseSolution.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_INVERSESOLUTION_H
#define DOBOT_BRINGUP_MESSAGE_INVERSESOLUTION_H

#include <ros/service_traits.h>


#include <dobot_bringup/InverseSolutionRequest.h>
#include <dobot_bringup/InverseSolutionResponse.h>


namespace dobot_bringup
{

struct InverseSolution
{

typedef InverseSolutionRequest Request;
typedef InverseSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseSolution
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::InverseSolution > {
  static const char* value()
  {
    return "ca1d2fdd189adb0efab2e962b8538e82";
  }

  static const char* value(const ::dobot_bringup::InverseSolution&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::InverseSolution > {
  static const char* value()
  {
    return "dobot_bringup/InverseSolution";
  }

  static const char* value(const ::dobot_bringup::InverseSolution&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::InverseSolutionRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::InverseSolution >
template<>
struct MD5Sum< ::dobot_bringup::InverseSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::InverseSolution >::value();
  }
  static const char* value(const ::dobot_bringup::InverseSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::InverseSolutionRequest> should match
// service_traits::DataType< ::dobot_bringup::InverseSolution >
template<>
struct DataType< ::dobot_bringup::InverseSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::InverseSolution >::value();
  }
  static const char* value(const ::dobot_bringup::InverseSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::InverseSolutionResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::InverseSolution >
template<>
struct MD5Sum< ::dobot_bringup::InverseSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::InverseSolution >::value();
  }
  static const char* value(const ::dobot_bringup::InverseSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::InverseSolutionResponse> should match
// service_traits::DataType< ::dobot_bringup::InverseSolution >
template<>
struct DataType< ::dobot_bringup::InverseSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::InverseSolution >::value();
  }
  static const char* value(const ::dobot_bringup::InverseSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_INVERSESOLUTION_H
