// Generated by gencpp from file dobot_bringup/ModbusCreate.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_MODBUSCREATE_H
#define DOBOT_BRINGUP_MESSAGE_MODBUSCREATE_H

#include <ros/service_traits.h>


#include <dobot_bringup/ModbusCreateRequest.h>
#include <dobot_bringup/ModbusCreateResponse.h>


namespace dobot_bringup
{

struct ModbusCreate
{

typedef ModbusCreateRequest Request;
typedef ModbusCreateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModbusCreate
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::ModbusCreate > {
  static const char* value()
  {
    return "81859286568c49567356da01e39e6422";
  }

  static const char* value(const ::dobot_bringup::ModbusCreate&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::ModbusCreate > {
  static const char* value()
  {
    return "dobot_bringup/ModbusCreate";
  }

  static const char* value(const ::dobot_bringup::ModbusCreate&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::ModbusCreateRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::ModbusCreate >
template<>
struct MD5Sum< ::dobot_bringup::ModbusCreateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ModbusCreate >::value();
  }
  static const char* value(const ::dobot_bringup::ModbusCreateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ModbusCreateRequest> should match
// service_traits::DataType< ::dobot_bringup::ModbusCreate >
template<>
struct DataType< ::dobot_bringup::ModbusCreateRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ModbusCreate >::value();
  }
  static const char* value(const ::dobot_bringup::ModbusCreateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::ModbusCreateResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::ModbusCreate >
template<>
struct MD5Sum< ::dobot_bringup::ModbusCreateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ModbusCreate >::value();
  }
  static const char* value(const ::dobot_bringup::ModbusCreateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ModbusCreateResponse> should match
// service_traits::DataType< ::dobot_bringup::ModbusCreate >
template<>
struct DataType< ::dobot_bringup::ModbusCreateResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ModbusCreate >::value();
  }
  static const char* value(const ::dobot_bringup::ModbusCreateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_MODBUSCREATE_H
