// Generated by gencpp from file dobot_bringup/ModbusCreateResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_MODBUSCREATERESPONSE_H
#define DOBOT_BRINGUP_MESSAGE_MODBUSCREATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct ModbusCreateResponse_
{
  typedef ModbusCreateResponse_<ContainerAllocator> Type;

  ModbusCreateResponse_()
    : res(0)
    , index(0)  {
    }
  ModbusCreateResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , index(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;

   typedef int32_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModbusCreateResponse_

typedef ::dobot_bringup::ModbusCreateResponse_<std::allocator<void> > ModbusCreateResponse;

typedef boost::shared_ptr< ::dobot_bringup::ModbusCreateResponse > ModbusCreateResponsePtr;
typedef boost::shared_ptr< ::dobot_bringup::ModbusCreateResponse const> ModbusCreateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator1> & lhs, const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator1> & lhs, const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "93ae6749f38850704528d34881ae033f";
  }

  static const char* value(const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x93ae6749f3885070ULL;
  static const uint64_t static_value2 = 0x4528d34881ae033fULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/ModbusCreateResponse";
  }

  static const char* value(const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 res\n"
"int32 index\n"
;
  }

  static const char* value(const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModbusCreateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::ModbusCreateResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_MODBUSCREATERESPONSE_H
