// Generated by gencpp from file dobot_bringup/MoveJogRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_MOVEJOGREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_MOVEJOGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct MoveJogRequest_
{
  typedef MoveJogRequest_<ContainerAllocator> Type;

  MoveJogRequest_()
    : axisID()
    , paramValue()  {
    }
  MoveJogRequest_(const ContainerAllocator& _alloc)
    : axisID(_alloc)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _axisID_type;
  _axisID_type axisID;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJogRequest_

typedef ::dobot_bringup::MoveJogRequest_<std::allocator<void> > MoveJogRequest;

typedef boost::shared_ptr< ::dobot_bringup::MoveJogRequest > MoveJogRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::MoveJogRequest const> MoveJogRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::MoveJogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::MoveJogRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::MoveJogRequest_<ContainerAllocator2> & rhs)
{
  return lhs.axisID == rhs.axisID &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::MoveJogRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::MoveJogRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57755273b7612f8d94b410dc31ef47b2";
  }

  static const char* value(const ::dobot_bringup::MoveJogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57755273b7612f8dULL;
  static const uint64_t static_value2 = 0x94b410dc31ef47b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/MoveJogRequest";
  }

  static const char* value(const ::dobot_bringup::MoveJogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string axisID\n"
"string[] paramValue\n"
;
  }

  static const char* value(const ::dobot_bringup::MoveJogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axisID);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::MoveJogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::MoveJogRequest_<ContainerAllocator>& v)
  {
    s << indent << "axisID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.axisID);
    s << indent << "paramValue[]" << std::endl;
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      s << indent << "  paramValue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.paramValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_MOVEJOGREQUEST_H
