// Generated by gencpp from file dobot_bringup/MovJExtRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_MOVJEXTREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_MOVJEXTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct MovJExtRequest_
{
  typedef MovJExtRequest_<ContainerAllocator> Type;

  MovJExtRequest_()
    : offset(0.0)
    , paramValue()  {
    }
  MovJExtRequest_(const ContainerAllocator& _alloc)
    : offset(0.0)
    , paramValue(_alloc)  {
  (void)_alloc;
    }



   typedef double _offset_type;
  _offset_type offset;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _paramValue_type;
  _paramValue_type paramValue;





  typedef boost::shared_ptr< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MovJExtRequest_

typedef ::dobot_bringup::MovJExtRequest_<std::allocator<void> > MovJExtRequest;

typedef boost::shared_ptr< ::dobot_bringup::MovJExtRequest > MovJExtRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::MovJExtRequest const> MovJExtRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::MovJExtRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::MovJExtRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::MovJExtRequest_<ContainerAllocator2> & rhs)
{
  return lhs.offset == rhs.offset &&
    lhs.paramValue == rhs.paramValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::MovJExtRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::MovJExtRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d5a53002335dbbd2c5fae368b7ea44c";
  }

  static const char* value(const ::dobot_bringup::MovJExtRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d5a53002335dbbdULL;
  static const uint64_t static_value2 = 0x2c5fae368b7ea44cULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/MovJExtRequest";
  }

  static const char* value(const ::dobot_bringup::MovJExtRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 offset\n"
"string[] paramValue\n"
;
  }

  static const char* value(const ::dobot_bringup::MovJExtRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset);
      stream.next(m.paramValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovJExtRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::MovJExtRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::MovJExtRequest_<ContainerAllocator>& v)
  {
    s << indent << "offset: ";
    Printer<double>::stream(s, indent + "  ", v.offset);
    s << indent << "paramValue[]" << std::endl;
    for (size_t i = 0; i < v.paramValue.size(); ++i)
    {
      s << indent << "  paramValue[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.paramValue[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_MOVJEXTREQUEST_H
