// Generated by gencpp from file dobot_bringup/PositiveSolution.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_POSITIVESOLUTION_H
#define DOBOT_BRINGUP_MESSAGE_POSITIVESOLUTION_H

#include <ros/service_traits.h>


#include <dobot_bringup/PositiveSolutionRequest.h>
#include <dobot_bringup/PositiveSolutionResponse.h>


namespace dobot_bringup
{

struct PositiveSolution
{

typedef PositiveSolutionRequest Request;
typedef PositiveSolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositiveSolution
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::PositiveSolution > {
  static const char* value()
  {
    return "8f42bcc802ab3546b7b7154a3d780925";
  }

  static const char* value(const ::dobot_bringup::PositiveSolution&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::PositiveSolution > {
  static const char* value()
  {
    return "dobot_bringup/PositiveSolution";
  }

  static const char* value(const ::dobot_bringup::PositiveSolution&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::PositiveSolutionRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::PositiveSolution >
template<>
struct MD5Sum< ::dobot_bringup::PositiveSolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::PositiveSolution >::value();
  }
  static const char* value(const ::dobot_bringup::PositiveSolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::PositiveSolutionRequest> should match
// service_traits::DataType< ::dobot_bringup::PositiveSolution >
template<>
struct DataType< ::dobot_bringup::PositiveSolutionRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::PositiveSolution >::value();
  }
  static const char* value(const ::dobot_bringup::PositiveSolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::PositiveSolutionResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::PositiveSolution >
template<>
struct MD5Sum< ::dobot_bringup::PositiveSolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::PositiveSolution >::value();
  }
  static const char* value(const ::dobot_bringup::PositiveSolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::PositiveSolutionResponse> should match
// service_traits::DataType< ::dobot_bringup::PositiveSolution >
template<>
struct DataType< ::dobot_bringup::PositiveSolutionResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::PositiveSolution >::value();
  }
  static const char* value(const ::dobot_bringup::PositiveSolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_POSITIVESOLUTION_H
