// Generated by gencpp from file dobot_bringup/RelMovL.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_RELMOVL_H
#define DOBOT_BRINGUP_MESSAGE_RELMOVL_H

#include <ros/service_traits.h>


#include <dobot_bringup/RelMovLRequest.h>
#include <dobot_bringup/RelMovLResponse.h>


namespace dobot_bringup
{

struct RelMovL
{

typedef RelMovLRequest Request;
typedef RelMovLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelMovL
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::RelMovL > {
  static const char* value()
  {
    return "78b4c768c0737ce432fc1dbbdd67429f";
  }

  static const char* value(const ::dobot_bringup::RelMovL&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::RelMovL > {
  static const char* value()
  {
    return "dobot_bringup/RelMovL";
  }

  static const char* value(const ::dobot_bringup::RelMovL&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::RelMovLRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovL >
template<>
struct MD5Sum< ::dobot_bringup::RelMovLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovL >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovLRequest> should match
// service_traits::DataType< ::dobot_bringup::RelMovL >
template<>
struct DataType< ::dobot_bringup::RelMovLRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovL >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::RelMovLResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovL >
template<>
struct MD5Sum< ::dobot_bringup::RelMovLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovL >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovLResponse> should match
// service_traits::DataType< ::dobot_bringup::RelMovL >
template<>
struct DataType< ::dobot_bringup::RelMovLResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovL >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_RELMOVL_H
