// Generated by gencpp from file dobot_bringup/RelMovJUser.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_RELMOVJUSER_H
#define DOBOT_BRINGUP_MESSAGE_RELMOVJUSER_H

#include <ros/service_traits.h>


#include <dobot_bringup/RelMovJUserRequest.h>
#include <dobot_bringup/RelMovJUserResponse.h>


namespace dobot_bringup
{

struct RelMovJUser
{

typedef RelMovJUserRequest Request;
typedef RelMovJUserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelMovJUser
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::RelMovJUser > {
  static const char* value()
  {
    return "7970102421ee401b86e32781f03dc410";
  }

  static const char* value(const ::dobot_bringup::RelMovJUser&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::RelMovJUser > {
  static const char* value()
  {
    return "dobot_bringup/RelMovJUser";
  }

  static const char* value(const ::dobot_bringup::RelMovJUser&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::RelMovJUserRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovJUser >
template<>
struct MD5Sum< ::dobot_bringup::RelMovJUserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovJUser >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovJUserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovJUserRequest> should match
// service_traits::DataType< ::dobot_bringup::RelMovJUser >
template<>
struct DataType< ::dobot_bringup::RelMovJUserRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovJUser >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovJUserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::RelMovJUserResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::RelMovJUser >
template<>
struct MD5Sum< ::dobot_bringup::RelMovJUserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::RelMovJUser >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovJUserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::RelMovJUserResponse> should match
// service_traits::DataType< ::dobot_bringup::RelMovJUser >
template<>
struct DataType< ::dobot_bringup::RelMovJUserResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::RelMovJUser >::value();
  }
  static const char* value(const ::dobot_bringup::RelMovJUserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_RELMOVJUSER_H
