// Generated by gencpp from file dobot_bringup/ServoJ.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_SERVOJ_H
#define DOBOT_BRINGUP_MESSAGE_SERVOJ_H

#include <ros/service_traits.h>


#include <dobot_bringup/ServoJRequest.h>
#include <dobot_bringup/ServoJResponse.h>


namespace dobot_bringup
{

struct ServoJ
{

typedef ServoJRequest Request;
typedef ServoJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoJ
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::ServoJ > {
  static const char* value()
  {
    return "b3602db62aec670111f5df6ff1c628d9";
  }

  static const char* value(const ::dobot_bringup::ServoJ&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::ServoJ > {
  static const char* value()
  {
    return "dobot_bringup/ServoJ";
  }

  static const char* value(const ::dobot_bringup::ServoJ&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::ServoJRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::ServoJ >
template<>
struct MD5Sum< ::dobot_bringup::ServoJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ServoJ >::value();
  }
  static const char* value(const ::dobot_bringup::ServoJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ServoJRequest> should match
// service_traits::DataType< ::dobot_bringup::ServoJ >
template<>
struct DataType< ::dobot_bringup::ServoJRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ServoJ >::value();
  }
  static const char* value(const ::dobot_bringup::ServoJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::ServoJResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::ServoJ >
template<>
struct MD5Sum< ::dobot_bringup::ServoJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ServoJ >::value();
  }
  static const char* value(const ::dobot_bringup::ServoJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ServoJResponse> should match
// service_traits::DataType< ::dobot_bringup::ServoJ >
template<>
struct DataType< ::dobot_bringup::ServoJResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ServoJ >::value();
  }
  static const char* value(const ::dobot_bringup::ServoJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_SERVOJ_H
