// Generated by gencpp from file dobot_bringup/SetTerminalKeys.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_SETTERMINALKEYS_H
#define DOBOT_BRINGUP_MESSAGE_SETTERMINALKEYS_H

#include <ros/service_traits.h>


#include <dobot_bringup/SetTerminalKeysRequest.h>
#include <dobot_bringup/SetTerminalKeysResponse.h>


namespace dobot_bringup
{

struct SetTerminalKeys
{

typedef SetTerminalKeysRequest Request;
typedef SetTerminalKeysResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTerminalKeys
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::SetTerminalKeys > {
  static const char* value()
  {
    return "e9885118d8baa0e46bd047b6deaa3f81";
  }

  static const char* value(const ::dobot_bringup::SetTerminalKeys&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::SetTerminalKeys > {
  static const char* value()
  {
    return "dobot_bringup/SetTerminalKeys";
  }

  static const char* value(const ::dobot_bringup::SetTerminalKeys&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::SetTerminalKeysRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::SetTerminalKeys >
template<>
struct MD5Sum< ::dobot_bringup::SetTerminalKeysRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::SetTerminalKeys >::value();
  }
  static const char* value(const ::dobot_bringup::SetTerminalKeysRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::SetTerminalKeysRequest> should match
// service_traits::DataType< ::dobot_bringup::SetTerminalKeys >
template<>
struct DataType< ::dobot_bringup::SetTerminalKeysRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::SetTerminalKeys >::value();
  }
  static const char* value(const ::dobot_bringup::SetTerminalKeysRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::SetTerminalKeysResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::SetTerminalKeys >
template<>
struct MD5Sum< ::dobot_bringup::SetTerminalKeysResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::SetTerminalKeys >::value();
  }
  static const char* value(const ::dobot_bringup::SetTerminalKeysResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::SetTerminalKeysResponse> should match
// service_traits::DataType< ::dobot_bringup::SetTerminalKeys >
template<>
struct DataType< ::dobot_bringup::SetTerminalKeysResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::SetTerminalKeys >::value();
  }
  static const char* value(const ::dobot_bringup::SetTerminalKeysResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_SETTERMINALKEYS_H
