// Generated by gencpp from file dobot_bringup/TcpDashboardRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_TCPDASHBOARDREQUEST_H
#define DOBOT_BRINGUP_MESSAGE_TCPDASHBOARDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot_bringup
{
template <class ContainerAllocator>
struct TcpDashboardRequest_
{
  typedef TcpDashboardRequest_<ContainerAllocator> Type;

  TcpDashboardRequest_()
    : command()  {
    }
  TcpDashboardRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TcpDashboardRequest_

typedef ::dobot_bringup::TcpDashboardRequest_<std::allocator<void> > TcpDashboardRequest;

typedef boost::shared_ptr< ::dobot_bringup::TcpDashboardRequest > TcpDashboardRequestPtr;
typedef boost::shared_ptr< ::dobot_bringup::TcpDashboardRequest const> TcpDashboardRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator1> & lhs, const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dobot_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot_bringup/TcpDashboardRequest";
  }

  static const char* value(const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TcpDashboardRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot_bringup::TcpDashboardRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_TCPDASHBOARDREQUEST_H
