// Generated by gencpp from file dobot_bringup/ToolDO.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_TOOLDO_H
#define DOBOT_BRINGUP_MESSAGE_TOOLDO_H

#include <ros/service_traits.h>


#include <dobot_bringup/ToolDORequest.h>
#include <dobot_bringup/ToolDOResponse.h>


namespace dobot_bringup
{

struct ToolDO
{

typedef ToolDORequest Request;
typedef ToolDOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToolDO
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::ToolDO > {
  static const char* value()
  {
    return "096263ad689c1ece47cec4376ad5d3b5";
  }

  static const char* value(const ::dobot_bringup::ToolDO&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::ToolDO > {
  static const char* value()
  {
    return "dobot_bringup/ToolDO";
  }

  static const char* value(const ::dobot_bringup::ToolDO&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::ToolDORequest> should match
// service_traits::MD5Sum< ::dobot_bringup::ToolDO >
template<>
struct MD5Sum< ::dobot_bringup::ToolDORequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ToolDO >::value();
  }
  static const char* value(const ::dobot_bringup::ToolDORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ToolDORequest> should match
// service_traits::DataType< ::dobot_bringup::ToolDO >
template<>
struct DataType< ::dobot_bringup::ToolDORequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ToolDO >::value();
  }
  static const char* value(const ::dobot_bringup::ToolDORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::ToolDOResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::ToolDO >
template<>
struct MD5Sum< ::dobot_bringup::ToolDOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::ToolDO >::value();
  }
  static const char* value(const ::dobot_bringup::ToolDOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::ToolDOResponse> should match
// service_traits::DataType< ::dobot_bringup::ToolDO >
template<>
struct DataType< ::dobot_bringup::ToolDOResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::ToolDO >::value();
  }
  static const char* value(const ::dobot_bringup::ToolDOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_TOOLDO_H
