// Generated by gencpp from file dobot_bringup/User.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_USER_H
#define DOBOT_BRINGUP_MESSAGE_USER_H

#include <ros/service_traits.h>


#include <dobot_bringup/UserRequest.h>
#include <dobot_bringup/UserResponse.h>


namespace dobot_bringup
{

struct User
{

typedef UserRequest Request;
typedef UserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct User
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::User > {
  static const char* value()
  {
    return "6d753c0adbdd6c06a6eb5c36aec96b0c";
  }

  static const char* value(const ::dobot_bringup::User&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::User > {
  static const char* value()
  {
    return "dobot_bringup/User";
  }

  static const char* value(const ::dobot_bringup::User&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::UserRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::User >
template<>
struct MD5Sum< ::dobot_bringup::UserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::User >::value();
  }
  static const char* value(const ::dobot_bringup::UserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::UserRequest> should match
// service_traits::DataType< ::dobot_bringup::User >
template<>
struct DataType< ::dobot_bringup::UserRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::User >::value();
  }
  static const char* value(const ::dobot_bringup::UserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::UserResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::User >
template<>
struct MD5Sum< ::dobot_bringup::UserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::User >::value();
  }
  static const char* value(const ::dobot_bringup::UserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::UserResponse> should match
// service_traits::DataType< ::dobot_bringup::User >
template<>
struct DataType< ::dobot_bringup::UserResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::User >::value();
  }
  static const char* value(const ::dobot_bringup::UserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_USER_H
