// Generated by gencpp from file dobot_bringup/Wait.msg
// DO NOT EDIT!


#ifndef DOBOT_BRINGUP_MESSAGE_WAIT_H
#define DOBOT_BRINGUP_MESSAGE_WAIT_H

#include <ros/service_traits.h>


#include <dobot_bringup/WaitRequest.h>
#include <dobot_bringup/WaitResponse.h>


namespace dobot_bringup
{

struct Wait
{

typedef WaitRequest Request;
typedef WaitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wait
} // namespace dobot_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot_bringup::Wait > {
  static const char* value()
  {
    return "ffdd33da4722c26f9e1ea1ac05b9a429";
  }

  static const char* value(const ::dobot_bringup::Wait&) { return value(); }
};

template<>
struct DataType< ::dobot_bringup::Wait > {
  static const char* value()
  {
    return "dobot_bringup/Wait";
  }

  static const char* value(const ::dobot_bringup::Wait&) { return value(); }
};


// service_traits::MD5Sum< ::dobot_bringup::WaitRequest> should match
// service_traits::MD5Sum< ::dobot_bringup::Wait >
template<>
struct MD5Sum< ::dobot_bringup::WaitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::Wait >::value();
  }
  static const char* value(const ::dobot_bringup::WaitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::WaitRequest> should match
// service_traits::DataType< ::dobot_bringup::Wait >
template<>
struct DataType< ::dobot_bringup::WaitRequest>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::Wait >::value();
  }
  static const char* value(const ::dobot_bringup::WaitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot_bringup::WaitResponse> should match
// service_traits::MD5Sum< ::dobot_bringup::Wait >
template<>
struct MD5Sum< ::dobot_bringup::WaitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot_bringup::Wait >::value();
  }
  static const char* value(const ::dobot_bringup::WaitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot_bringup::WaitResponse> should match
// service_traits::DataType< ::dobot_bringup::Wait >
template<>
struct DataType< ::dobot_bringup::WaitResponse>
{
  static const char* value()
  {
    return DataType< ::dobot_bringup::Wait >::value();
  }
  static const char* value(const ::dobot_bringup::WaitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_BRINGUP_MESSAGE_WAIT_H
